version: "3.8"

services:

  postgres:
    image: postgres:14
    container_name: bank-postgres
    environment:
      POSTGRES_DB: e_banking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  demobank_springboot:
    image: banking_app:latest
    container_name: demobank-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/e_banking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres

  demobank_react:
    image: demobank_react_v2:latest
    container_name: demobank-frontend
    ports:
      - "3000:3000"

volumes:
  postgres-data:
